extract_survey_number <- function(lines_of_text) {
  res <-
    stringr::str_match(
      stringr::str_replace_all(paste(lines_of_text, collapse = " "), "\n0", ""),
      "CARD 1.*(PLANNING [Ss][Uu][Rr][Vv][Ee][Yy]|[Ss][Uu][Rr][Vv][Ee][Yy] [Nn][Uu][Mm][Bb][Ee][Rr]).*?[Cc][Oo][Ll][Ss]\\.?\\ ?([0-9]-[0-9])"
    )[3]
  sc_start_end <- as.numeric(str_split(res, "-")[[1]])
  return(sc_start_end)
}


# codebook_lines <- import_codebook_file("data/original/Attitudes of Combat Infantry Officers (AMS-101), January-April 1944/Technical Documentation/AMS-101F_ Attitudes of Combat Infantry Officers, codebook.AMS101F.CDBK")
# codebook_lines <- import_codebook_file("data/original/Attitudes of Combat Infantry Officers (AMS-101), January-April 1944/Technical Documentation/AMS-101E_ Attitudes of Combat Infantry Officers, codebook.AMS101E.CDBK")
# codebook_lines <- import_codebook_file("data/original/Attitudes of WACS (AMS-194), February 1945/Technical Documentation/AMS-194_ Attitudes of WACS 02_1945, codebook.AMS0194.CDBK")
# codebook_lines <- import_codebook_file("data/original/Planning Survey for Attitudes toward Medical Care (PS-4), October 1942/Technical Documentation/PS-4_ Planning for Attitudes toward Medical Care, codebook.AMSPS04.CDBK")
# codebook_lines <- import_codebook_file("data/original/Attitudes of (or towards) Negroes (PS-32), March 1943/Technical Documentation/PS-32N_ Attitudes of Negroes, codebook.AMS032N.CDBK")
# extract_survey_number(codebook_lines)

# txt1 <- "
# 0        ROPER CENTER - AMS101E                      PAGE   5                    
# 0                                                                                
# 0                CARD 1                                                          
# 0                CARD.                                                           
# 0                C. COL. 1.                                                      
# 0           177   1. CARD ONE                                                    
# 0                DECK.                                                           
# 0                Y. COLS. 2-4.                                                   
# 0         101. SURVEY NUMBER                                                     
# 0                BALLOT.                                                         
# 0                Y. COLS. 5-7.                                                   
# 0                X. BALLOT NUMBER GENERATED BY ROPER CENTER.                     
# 0                FORM.                                                           
# 0                Y. COL. 8.     
# "
# 
# txt2 <- "
# 1                                                                                
# 0        ROPER CENTER - AMS101F                      PAGE   5                    
# 0                                                                                
# 0                CARD 1                                                          
# 0                CARD.                                                           
# 0                C. COL. 1.                                                      
# 0            92   1. CARD ONE                                                    
# 0                DECK.                                                           
# 0                Y. COLS. 2-4.                                                   
# 0         101. SURVEY NUMBER                                                     
# 0                BALLOT.                                                         
# 0                Y. COLS. 5-6.                                                   
# 0                X. BALLOT NUMBER GENERATED BY ROPER CENTER.                     
# 0                FORM.                                                           
# 0                Y. COL. 7.                     
# "
# 
# txt3 <- "
#                      X.        RPORC COMMENTS                                    
# 1                                                                                
# 0        ROPER CENTER - AMS0194                      PAGE   5                    
# 0                                                                                
# 0                CARD 1                                                          
# 0                CARD.                                                           
# 0                C. COL. 1.                                                      
# 0          6658   1. CARD ONE                                                    
# 0                DECK.                                                           
# 0                Y. COLS. 2-4.                                                   
# 0         194. SURVEY NUMBER                                                     
# 0                BALLOT.                                                         
# 0                Y. COLS. 5-8.                                                   
# 0                X. BALLOT NUMBER GENERATED BY ROPER CENTER.                     
# 0                Q.1. WHAT IS YOUR ARMY RANK OR GRADE*                           
# 0                R. COLS. 9-10.   
# "
# 
# 
# 
# 
