fix_apostrophes <- function(str_v) {
  str_replace_all(str_v, "([A-Z]),([A-Z])", "\\1'\\2")
}

fix_asterisks <- function(str_v) {
  q_lns <- str_which(str_v, "^Q")
  for (ln in q_lns) {
    str_v[ln] <- str_replace_all(str_v[ln], "[a-zA-Z ]\\*( |\\.|\\))", "?\\1")
  }
  v_lns <- str_which(str_v, "^V")
  for (ln in v_lns) {
    str_v[ln] <- str_replace_all(str_v[ln], "[a-zA-Z ]\\*( |\\.|\\))", "\\1")
  }
  str_v  
}

fix_oddities <- function(str_v) {
  fix_apostrophes(str_v) %>% fix_asterisks()  
}

# 
# s <- "Q.63A. (DO YOU THINK WHITE AND NEGRO SOLDIERS SHOULD BE IN SEPARATE OUTFITS OR SHOULD THEY BE TOGETHER IN THE SAME OUTFITS*) WRITE ANY COMMENTS HERE: C. COLS. 66-67. 168 01. SEPARATE OUTFITS OUT OF DEFERENCE TO SOUTHERN CUSTOMS (IT,S O.K. FOR SOUTH, BUT NOT FOR NORTH, NOT WHERE THIS CAMP IS LOCATED) 350 02. SEPARATE OUTFITS BECAUSE INTERMINGLING WOULD LEAD TO VIOLENCE, FIGHTS, TROUBLE 95 03. SEPARATE OUTFITS BECAUSE NEGROES THEMSELVES (OR BOTH NEGROES AND WHITES) LIKE IT BETTER THAT WAY (NEGROES FEEL UNCOMFORTABLE WITH WHITES, NEGROES FEEL MORE AT HOME WITH OWN RACE) 69 04. SEPARATE OUTFITS BECAUSE WHITES DISLIKE OR ARE UNWILLING TO ASSOCIATE WITH NEGROES (WE FEEL BETTER WITHOUT THEM AROUND, WILL KEEP WHITES FROM BEING EMBARRASSED) 22 05. SEPARATE OUTFITS BECAUSE NEGROES ARE INFERIOR TO WHITES (THEY ARE NOT AS GOOD AS WHITES, THEY SHOULD NOT BE CLASSED WITH WHITES) 189 06. SEPARATE OUTFITS BECAUSE SEPARATION IS RIGHT IN PRINCIPLE (RACES SHOULD BE KEPT SEPARATE, THE NEGRO IS O.K. ON HIS SIDE OF THE FENCE) 79 07. SEPARATE OUTFITS BECAUSE I PERSONALLY DISLIKE OR OBJECT TO NEGROES (I JUST DON,T LIKE NEGROES, I DON,T WANT TO LIVE WITH NEGROES) 60 08. SEPARATE OUTFITS AND CRITICISMS OF NEGROES (THEY SMELL BAD, THEY CARRY DISEASES) 107 09. SEPARATE OUTFITS AND SOME OTHER COMMENT 2838 10. SEPARATE OUTFITS AND NO COMMENT 57 11. IT DOESN,T MAKE ANY DIFFERENCE WITH OR WITHOUT COMMENT 589 12. SHOULD BE TOGETHER IN SAME OUTFITS 170 13. NO ANSWER TO Q.63 OR UNDECIDED X. Q.64 NOT CODED BY SURVEY ORGANIZATION. "
# 
# 
# fix_asterisks(s)
